apiVersion: apps/v1
kind: Deployment  
metadata :
  name: service1
  labels:
   app: service1
spec:
  replicas: 1      
  selector: 
   matchLabels:
    app: service1 
  template:
   metadata: 
    labels: 
     app: service1
   spec:
    containers:
    - name: service1
      image: pstyp94/service1
      ports:
      - containerPort: 5000
      env: 
      - name: PASSWORD
        value: root
        name: DATABASE
        value: mysql+pymysql://root:root@mysql:3306/flask-db
   
---      
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service2
  labels:
   app: service2
spec:
  replicas: 1      
  selector:
   matchLabels: 
    app: service2 
  template:
   metadata:
    labels:
     app: service2
   spec:
    containers: 
    - name: service2
      image: pstyp94/service2
      ports:
      - containerPort: 5001


---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: service3  
  labels:
   app: service3 
spec:
  replicas: 1      
  selector:
   matchLabels: 
    app: service3
  template:
   metadata:
    labels:
     app: service3
   spec:  
    containers:
    - name: service3
      image: pstyp94/service3
      ports:
      - containerPort: 5002  


  
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: service4
  labels: 
   app: service4
spec:
  replicas: 1      
  selector:
   matchLabels:
    app: service4
  template:
   metadata:
    labels:
     app: service4
   spec: 
    containers:
    - name: service4
      image: pstyp94/service4
      ports:
      - containerPort: 5003
      env:
      - name: PASSWORD
        value: root
      - name: DATABASE
        value: mysql+pymysql://root:root@mysql:3306/flask-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql 
  labels:
   app: mysql
spec:
  replicas: 1
  selector:
   matchLabels:
    app: mysql
  template:
   metadata:
    labels:
     app: mysql
   spec:
    containers:
    - name: mysql
      image: mysql:5.7
      ports:
      - containerPort: 3306
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: MYSQL_DATABASE
        value: flask-db



---
